try:
    import sys
    import pysqlite3
    sys.modules["sqlite3"] = pysqlite3
except ImportError:
    pass

from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any
import asyncio
import json
import os
import sqlite3
import traceback
import uuid
from datetime import datetime

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / ".env")

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from langchain_core.messages import HumanMessage, AIMessage
from pydantic import BaseModel, Field

from create_schema import create_database
from my_agent.agent import build_graph
from my_agent.utils.ollama_check import chat_model_name, check_ollama
from my_agent.utils.tools import cleanup_tools


DB_PATH = os.path.join(os.path.dirname(__file__), "database", "schema.db")
HISTORY_DB_PATH = os.path.join(os.path.dirname(__file__), "database", "chat_history.db")


# Mapping of active request IDs to their running asyncio Tasks
active_tasks: dict[str, asyncio.Task] = {}


class AskRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Natural-language question.")
    request_id: str | None = Field(
        None,
        description="Unique ID generated by the UI to track and cancel this request.",
    )
    session_id: str | None = Field(default=None, description="Optional chat session ID for conversation memory.")
    thread_id: str | None = Field(default=None, description="Optional chat thread ID (alias for session_id) for conversation memory.")
    username: str | None = Field(default=None, description="Optional username to scope the chat history.")


class AskResponse(BaseModel):
    sql: str
    result: list[dict[str, Any]]
    session_id: str | None = Field(default=None, description="The session ID associated with this chat.")


class SessionSummary(BaseModel):
    id: str
    title: str
    created_at: str
    updated_at: str


class MessageDetail(BaseModel):
    id: str
    role: str
    content: str
    sql: str | None = None
    result: list[dict[str, Any]] | None = None
    created_at: str


class SessionDetail(BaseModel):
    id: str
    title: str
    created_at: str
    updated_at: str
    messages: list[MessageDetail]


def init_database() -> None:
    """Initialize curated sample database if missing or still on the old schema."""
    should_create = not os.path.exists(DB_PATH)
    if not should_create:
        try:
            conn = sqlite3.connect(DB_PATH)
            tables = {
                row[0]
                for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
            }
            conn.close()
            should_create = "citizen_student" not in tables or "students" in tables
        except sqlite3.Error:
            should_create = True

    if should_create:
        create_database(DB_PATH, replace=True)
        print(f"Curated database initialized at {DB_PATH}")


def init_history_database() -> None:
    """Initialize SQLite database for chat history and sessions."""
    os.makedirs(os.path.dirname(HISTORY_DB_PATH), exist_ok=True)
    conn = sqlite3.connect(HISTORY_DB_PATH)
    try:
        conn.execute("PRAGMA foreign_keys = ON;")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                username TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS messages (
                id TEXT PRIMARY KEY,
                session_id TEXT NOT NULL,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                sql TEXT,
                result TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
            );
        """)
        try:
            conn.execute("ALTER TABLE sessions ADD COLUMN username TEXT;")
        except sqlite3.OperationalError:
            pass
        conn.commit()
        print(f"Chat history database initialized at {HISTORY_DB_PATH}")
    except sqlite3.Error as e:
        print(f"Error initializing chat history database: {e}")
    finally:
        conn.close()


def get_session_messages(session_id: str) -> list[Any]:
    """Load messages from db and convert them to LangGraph message list."""
    conn = sqlite3.connect(HISTORY_DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT role, content FROM messages WHERE session_id = ? ORDER BY created_at DESC LIMIT 10",
            (session_id,)
        )
        rows = cursor.fetchall()
        rows.reverse()
        messages = []
        for row in rows:
            if row["role"] == "user":
                messages.append(HumanMessage(content=row["content"]))
            elif row["role"] == "assistant":
                messages.append(AIMessage(content=row["content"]))
        return messages
    except sqlite3.Error as e:
        print(f"Database error while reading session messages: {e}")
        return []
    finally:
        conn.close()


def save_chat_turn(session_id: str, question: str, response_text: str, sql: str | None, result: list[dict[str, Any]] | None, username: str | None = None) -> str:
    """Save user and assistant messages, update session updated_at, return session_id."""
    conn = sqlite3.connect(HISTORY_DB_PATH)
    now = datetime.now().isoformat()
    try:
        cursor = conn.cursor()
        
        # Check if session exists
        cursor.execute("SELECT id FROM sessions WHERE id = ?", (session_id,))
        session_exists = cursor.fetchone() is not None
        
        if not session_exists:
            # Generate a title from the first question (first 60 chars)
            title = question[:60] + ("..." if len(question) > 60 else "")
            cursor.execute(
                "INSERT INTO sessions (id, title, username, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                (session_id, title, username, now, now)
            )
        else:
            # Update updated_at
            cursor.execute(
                "UPDATE sessions SET updated_at = ? WHERE id = ?",
                (now, session_id)
            )
            if username:
                cursor.execute(
                    "UPDATE sessions SET username = ? WHERE id = ? AND username IS NULL",
                    (username, session_id)
                )
            
        # Save user message
        user_msg_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO messages (id, session_id, role, content, created_at) VALUES (?, ?, ?, ?, ?)",
            (user_msg_id, session_id, "user", question, now)
        )
        
        # Save assistant message
        assistant_msg_id = str(uuid.uuid4())
        result_json = json.dumps(result) if result is not None else None
        cursor.execute(
            "INSERT INTO messages (id, session_id, role, content, sql, result, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (assistant_msg_id, session_id, "assistant", response_text, sql, result_json, now)
        )
        
        conn.commit()
        return session_id
    except sqlite3.Error as e:
        print(f"Database error while saving chat turn: {e}")
        return session_id
    finally:
        conn.close()


def _http_error_from_exc(exc: Exception) -> HTTPException:
    msg = str(exc)
    model = chat_model_name()
    if "not found" in msg.lower() and "model" in msg.lower():
        return HTTPException(
            status_code=503,
            detail=(
                f"Ollama model '{model}' is not installed. "
                f"Run: ollama pull {model} - then restart uvicorn. ({msg})"
            ),
        )
    return HTTPException(status_code=500, detail=msg)


def _extract_tool_content(message: Any) -> str | None:
    """Extract plain-text content from a ToolMessage.

    MCP adapters may deliver content as a plain string OR as a list of
    content blocks (e.g. [{"type": "text", "text": "..."}]).  Handle both.
    """
    raw = getattr(message, "content", None)
    if raw is None:
        return None
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        for item in raw:
            if isinstance(item, str):
                return item
            if isinstance(item, dict) and item.get("type") == "text":
                return item.get("text")
    return str(raw)


def _extract_sql_and_result(messages: list[Any]) -> AskResponse:
    from langchain_core.messages import ToolMessage as LCToolMessage

    sql = None
    result: list[dict[str, Any]] | None = None

    for message in messages:
        # ── extract SQL from any AIMessage tool call ──────────────────────────
        for tool_call in getattr(message, "tool_calls", None) or []:
            args = tool_call.get("args") or {}
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except json.JSONDecodeError:
                    args = {}
            if tool_call.get("name") == "execute_sql" and args.get("query"):
                sql = args["query"]

        # ── extract rows from any execute_sql ToolMessage ─────────────────────
        is_tool_msg = isinstance(message, LCToolMessage) or (
            message.__class__.__name__ == "ToolMessage"
        )
        if not is_tool_msg:
            continue

        tool_name = getattr(message, "name", None)
        if tool_name != "execute_sql":
            continue

        raw_content = _extract_tool_content(message)
        if not raw_content:
            continue

        try:
            payload = json.loads(raw_content)
        except (json.JSONDecodeError, TypeError, ValueError):
            continue

        if payload.get("status") == "success":
            result = payload.get("rows") or []

    # If SQL was not found, default to empty string
    if sql is None:
        sql = ""

    # If result was not found (meaning failure or no execution), build a fallback explanation result
    if result is None:
        error_msg = None
        # Try to find an error status in execute_sql ToolMessages
        for message in reversed(messages):
            is_tool_msg = isinstance(message, LCToolMessage) or (
                message.__class__.__name__ == "ToolMessage"
            )
            if is_tool_msg and getattr(message, "name", None) == "execute_sql":
                raw_content = _extract_tool_content(message)
                if raw_content:
                    try:
                        payload = json.loads(raw_content)
                        if payload.get("status") == "error":
                            error_msg = payload.get("error_msg") or payload.get("error_type")
                            if error_msg:
                                break
                    except Exception:
                        pass

        # If no tool error, look for any final explanation AIMessage
        if not error_msg:
            for message in reversed(messages):
                msg_class = message.__class__.__name__
                if msg_class == "AIMessage" or getattr(message, "content", None):
                    # Make sure it's not a tool call message
                    if not getattr(message, "tool_calls", None):
                        content = getattr(message, "content", None)
                        if content and isinstance(content, str) and content.strip():
                            error_msg = content.strip()
                            break

        if not error_msg:
            error_msg = "The agent did not return an executed SQL query."

        result = [{"error": error_msg, "status": "failed"}]

    return AskResponse(sql=sql, result=result)



@asynccontextmanager
async def lifespan(app: FastAPI):
    init_database()
    init_history_database()
    ollama_status = check_ollama()
    app.state.ollama_status = ollama_status
    app.state.graph = None
    app.state.graph_lock = asyncio.Lock()
    if not ollama_status.get("model_available"):
        print("WARNING: Ollama chat model not available:", ollama_status)
    else:
        print("Ollama ready:", ollama_status.get("model"))
        try:
            app.state.graph = await build_graph()
            print("LangGraph agent built successfully during startup.")
        except Exception as e:
            app.state.graph = None
            print(f"Failed to build LangGraph agent during startup: {e}")
            traceback.print_exc()

    yield
    if app.state.graph is not None:
        await cleanup_tools()


async def _get_graph():
    if app.state.graph is None:
        async with app.state.graph_lock:
            if app.state.graph is None:
                app.state.graph = await build_graph()
    return app.state.graph


# Global lock to serialize requests and prevent concurrency crashes in Milvus/MCP
request_lock = asyncio.Lock()

app = FastAPI(
    title="Curated Datamodels API",
    version="1.0.0",
    description="API-only backend for natural-language SQL over curated sample data.",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    info = check_ollama()
    return {
        "status": "ok" if info.get("model_available") else "degraded",
        **info,
    }


class CancelRequest(BaseModel):
    request_id: str = Field(..., description="The unique ID of the request to cancel.")


@app.post("/cancel")
async def cancel_request(payload: CancelRequest):
    req_id = payload.request_id
    task = active_tasks.get(req_id)
    if task:
        task.cancel()
        return {"status": "success", "message": f"Request {req_id} cancellation signal sent."}
    return {
        "status": "not_found",
        "message": f"Request {req_id} is not active or has already completed.",
    }


@app.post("/ask")
async def ask(payload: AskRequest):
    req_id = payload.request_id or f"req_{asyncio.get_running_loop().time()}"
    session_id = payload.session_id or payload.thread_id or str(uuid.uuid4())
    username = payload.username
    history_messages = get_session_messages(session_id)

    async def _stream():
        graph_task: asyncio.Task | None = None
        try:
            if not check_ollama().get("model_available"):
                yield json.dumps({
                    "sql": "",
                    "result": [{"error": (
                        f"Ollama model '{chat_model_name()}' is not available. "
                        f"Run: ollama pull {chat_model_name()} — then restart uvicorn."
                    ), "status": "failed"}],
                }).encode()
                return

            graph = await _get_graph()

            # Run the graph inside the request lock in a background task so we
            # can send periodic keepalive bytes while it works.  IIS (and any
            # reverse proxy) resets its idle-connection timer on every byte
            # received, so this prevents the 502 from triggering before the
            # graph finishes.
            async def _run_graph():
                async with request_lock:
                    return await graph.ainvoke(
                        {
                            "user_query": payload.question,
                            "messages": history_messages + [HumanMessage(content=payload.question)],
                            "retrieved_context": [],
                            "llm_calls": 0,
                            "verify_calls": 0,
                            "verified": False,
                        }
                    )

            graph_task = asyncio.ensure_future(_run_graph())
            active_tasks[req_id] = graph_task

            # Keepalive loop: check if the graph task is done every 0.1 seconds.
            # Every 10 seconds, send a keepalive space to reset IIS proxy timeouts.
            KEEPALIVE_INTERVAL = 10.0
            POLL_INTERVAL = 0.1
            elapsed = 0.0
            while not graph_task.done():
                await asyncio.sleep(POLL_INTERVAL)
                elapsed += POLL_INTERVAL
                if elapsed >= KEEPALIVE_INTERVAL:
                    yield b" "  # keepalive — resets IIS 120 s proxy timeout
                    elapsed = 0.0

            # Retrieve result (re-raises any exception from inside the task)
            state = graph_task.result()
            response_obj = _extract_sql_and_result(state.get("messages", []))

            # Extract response text (the final assistant verbal summary)
            response_text = ""
            for msg in reversed(state.get("messages", [])):
                if msg.__class__.__name__ == "AIMessage" or getattr(msg, "type", None) == "ai":
                    if not getattr(msg, "tool_calls", None) and getattr(msg, "content", ""):
                        response_text = msg.content
                        break
            if not response_text:
                if response_obj.result and isinstance(response_obj.result, list) and len(response_obj.result) > 0 and "error" in response_obj.result[0]:
                    response_text = response_obj.result[0]["error"]
                else:
                    response_text = "Here is the query result."

            # Save user query and assistant response to chat history database
            save_chat_turn(
                session_id=session_id,
                question=payload.question,
                response_text=response_text,
                sql=response_obj.sql,
                result=response_obj.result,
                username=username
            )

            response_obj.session_id = session_id

            yield json.dumps(response_obj.model_dump()).encode()

        except BaseException as exc:
            cancelled = (
                (graph_task is not None and graph_task.cancelled())
                or isinstance(exc, asyncio.CancelledError)
            )
            if cancelled:
                print(f"Request {req_id} was explicitly cancelled.")
                yield json.dumps({"sql": "", "result": [{"error": "Request cancelled.", "status": "cancelled"}]}).encode()
            else:
                traceback.print_exc()
                yield json.dumps({"sql": "", "result": [{"error": str(exc), "status": "failed"}]}).encode()

        finally:
            active_tasks.pop(req_id, None)

    return StreamingResponse(
        _stream(),
        media_type="application/json",
    )


@app.get("/history", response_model=list[SessionSummary])
async def get_history_sessions(username: str | None = None):
    conn = sqlite3.connect(HISTORY_DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        cursor = conn.cursor()
        if username:
            cursor.execute("SELECT id, title, created_at, updated_at FROM sessions WHERE username = ? ORDER BY updated_at DESC", (username,))
        else:
            cursor.execute("SELECT id, title, created_at, updated_at FROM sessions ORDER BY updated_at DESC")
        rows = cursor.fetchall()
        return [
            SessionSummary(
                id=row["id"],
                title=row["title"],
                created_at=row["created_at"],
                updated_at=row["updated_at"]
            )
            for row in rows
        ]
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch chat history: {e}")
    finally:
        conn.close()


@app.get("/history/{session_id}", response_model=SessionDetail)
async def get_history_session_detail(session_id: str):
    conn = sqlite3.connect(HISTORY_DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT id, title, created_at, updated_at FROM sessions WHERE id = ?", (session_id,))
        session_row = cursor.fetchone()
        if not session_row:
            raise HTTPException(status_code=404, detail="Chat session not found")

        cursor.execute(
            "SELECT id, role, content, sql, result, created_at FROM messages WHERE session_id = ? ORDER BY created_at ASC",
            (session_id,)
        )
        msg_rows = cursor.fetchall()

        messages = []
        for r in msg_rows:
            sql_val = r["sql"]
            res_val = None
            if r["result"]:
                try:
                    res_val = json.loads(r["result"])
                except Exception:
                    res_val = []
            messages.append(
                MessageDetail(
                    id=r["id"],
                    role=r["role"],
                    content=r["content"],
                    sql=sql_val,
                    result=res_val,
                    created_at=r["created_at"]
                )
            )

        return SessionDetail(
            id=session_row["id"],
            title=session_row["title"],
            created_at=session_row["created_at"],
            updated_at=session_row["updated_at"],
            messages=messages
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch session detail: {e}")
    finally:
        conn.close()


@app.delete("/history/{session_id}")
async def delete_history_session(session_id: str):
    conn = sqlite3.connect(HISTORY_DB_PATH)
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT id FROM sessions WHERE id = ?", (session_id,))
        if not cursor.fetchone():
            raise HTTPException(status_code=404, detail="Chat session not found")

        cursor.execute("DELETE FROM messages WHERE session_id = ?", (session_id,))
        cursor.execute("DELETE FROM sessions WHERE id = ?", (session_id,))
        conn.commit()
        return {"status": "success", "message": "Session deleted successfully"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete session: {e}")
    finally:
        conn.close()


@app.delete("/history")
async def clear_all_history_sessions(username: str | None = None):
    conn = sqlite3.connect(HISTORY_DB_PATH)
    try:
        cursor = conn.cursor()
        if username:
            cursor.execute("DELETE FROM messages WHERE session_id IN (SELECT id FROM sessions WHERE username = ?)", (username,))
            cursor.execute("DELETE FROM sessions WHERE username = ?", (username,))
        else:
            cursor.execute("DELETE FROM messages")
            cursor.execute("DELETE FROM sessions")
        conn.commit()
        return {"status": "success", "message": "All sessions deleted successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear sessions: {e}")
    finally:
        conn.close()
