database: curated_datamodels
title: Curated Hive/Iceberg Data Models
description: Curated Hive/Iceberg data model organized by HDFS location domains such
  as school, gsws, and canonicalmodel.
source_ddl:
- C:\Users\2797779\Downloads\curated_datamodels_ddls.txt
full_schema: full_schema.yaml
tables_dir: tables
tables:
- absent_reason_dim
- assessment_dim
- beneficiary_type_dim
- benefit_type_dim
- citizen_address_master
- citizen_address_master_test
- citizen_agriculture_land
- citizen_asset_electricity
- citizen_asset_vaahan
- citizen_asset_vaahan_type
- citizen_bank_accounts
- citizen_consent
- citizen_document
- citizen_document_testing
- citizen_education
- citizen_family_master
- citizen_health_schemes
- citizen_health_schemes_master
- citizen_idty
- citizen_idty_type
- citizen_land
- citizen_master
- citizen_property
- citizen_school
- citizen_school_teacher
- citizen_student
- citizen_utility_connection
- citizen_welfare_schemes
- citizen_welfare_schemes_master
- core_temple_auvs_summary_tab_test_dummy
- core_temple_ddns
- core_temple_ddrf_test_dummy
- govt_emp_data
- gsws_caste_religion_master
- gsws_cluster_master
- gsws_demographic_details
- gsws_hh_sixstep_cal
- gsws_hh_volunteer_mapping
- gsws_relation_masters
- gsws_revenue_village_map
- gsws_sec_building_lat_longs
- gsws_sec_secretariat_accdtls
- gsws_sec_secretariat_master
- gsws_sec_sim_mobile_details
- gws_citizen_bank_dtls_tab
- gws_cluster_map_tab
- gws_constiuency_sec_master
- gws_death_capture_tab
- gws_district_master
- gws_emp_hh_cap_geo_cor_tab
- gws_hh_mem_data
- gws_lgd_mdl_rev_master
- gws_mauddata
- health_scheme_code
- infrastructure_category_dim
- infrastructure_component_dim
- meal_type_dim
- mid_day_meal_serving_fact
- nutrition_item_dim
- oracle_temp_data_nopkey_1_dummy
- ration_card_citizen
- ration_card_citizen_reason
- ration_card_family
- ration_card_type
- scheme_benefits_fact
- school_academic_performance_fact
- school_category
- school_infra_category_dim
- school_infra_component_dim
- school_infrastructure_progress_fact
- school_meal_menu_dim
- school_medium
- school_scheme_master
- school_student_attendance_fact
- school_subject_master
- school_teacher_attendance_fact
- secretariate_employee_details
- source_department_code
- student_class_dim
- welfare_schemes_life_cycle
