try:
    import sys
    import pysqlite3
    sys.modules["sqlite3"] = pysqlite3
except ImportError:
    pass

from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any
import asyncio
import json
import os
import sqlite3
import traceback
import uuid
from datetime import datetime

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / ".env")

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse, HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from langchain_core.messages import HumanMessage, AIMessage
from pydantic import BaseModel, Field

from create_schema import create_database
from my_agent.agent import build_graph
from my_agent.utils.ollama_check import chat_model_name, check_ollama
from my_agent.utils.tools import cleanup_tools


DB_PATH = os.path.join(os.path.dirname(__file__), "database", "schema.db")
HISTORY_DB_PATH = os.path.join(os.path.dirname(__file__), "database", "chat_history.db")


# Mapping of active request IDs to their running asyncio Tasks
active_tasks: dict[str, asyncio.Task] = {}


class AskRequest(BaseModel):
    action: str | None = Field(default=None, description="Action to perform: 'ask', 'cancel', 'history', 'history_session', 'delete_session', 'clear_history'")
    question: str | None = Field(default=None, description="Natural-language question.")
    request_id: str | None = Field(
        None,
        description="Unique ID generated by the UI to track and cancel this request.",
    )
    session_id: str | None = Field(default=None, description="Optional chat session ID for conversation memory.")
    thread_id: str | None = Field(default=None, description="Optional chat thread ID (alias for session_id) for conversation memory.")
    username: str = Field(..., min_length=1, description="Required username to scope the chat history.")


class AskResponse(BaseModel):
    sql: str
    result: list[dict[str, Any]]
    username: str = Field(..., description="The username associated with this chat.")


class SessionSummary(BaseModel):
    id: str
    title: str
    created_at: str
    updated_at: str


class MessageDetail(BaseModel):
    id: str
    role: str
    content: str
    sql: str | None = None
    result: list[dict[str, Any]] | None = None
    created_at: str


class SessionDetail(BaseModel):
    id: str
    title: str
    created_at: str
    updated_at: str
    messages: list[MessageDetail]


def init_database() -> None:
    """Initialize curated sample database if missing or still on the old schema."""
    should_create = not os.path.exists(DB_PATH)
    if not should_create:
        try:
            conn = sqlite3.connect(DB_PATH)
            tables = {
                row[0]
                for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
            }
            conn.close()
            should_create = "citizen_student" not in tables or "students" in tables
        except sqlite3.Error:
            should_create = True

    if should_create:
        create_database(DB_PATH, replace=True)
        print(f"Curated database initialized at {DB_PATH}")


def init_history_database() -> None:
    """Initialize SQLite database for chat history and sessions."""
    os.makedirs(os.path.dirname(HISTORY_DB_PATH), exist_ok=True)
    conn = sqlite3.connect(HISTORY_DB_PATH)
    try:
        conn.execute("PRAGMA foreign_keys = ON;")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                username TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS messages (
                id TEXT PRIMARY KEY,
                session_id TEXT NOT NULL,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                sql TEXT,
                result TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
            );
        """)
        try:
            conn.execute("ALTER TABLE sessions ADD COLUMN username TEXT;")
        except sqlite3.OperationalError:
            pass
        conn.commit()
        print(f"Chat history database initialized at {HISTORY_DB_PATH}")
    except sqlite3.Error as e:
        print(f"Error initializing chat history database: {e}")
    finally:
        conn.close()


def get_session_messages(session_id: str) -> list[Any]:
    """Load messages from db and convert them to LangGraph message list."""
    conn = sqlite3.connect(HISTORY_DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT role, content FROM messages WHERE session_id = ? ORDER BY created_at DESC LIMIT 10",
            (session_id,)
        )
        rows = cursor.fetchall()
        rows.reverse()
        messages = []
        for row in rows:
            if row["role"] == "user":
                messages.append(HumanMessage(content=row["content"]))
            elif row["role"] == "assistant":
                messages.append(AIMessage(content=row["content"]))
        return messages
    except sqlite3.Error as e:
        print(f"Database error while reading session messages: {e}")
        return []
    finally:
        conn.close()


def save_chat_turn(session_id: str, question: str, response_text: str, sql: str | None, result: list[dict[str, Any]] | None, username: str | None = None) -> str:
    """Save user and assistant messages, update session updated_at, return session_id."""
    conn = sqlite3.connect(HISTORY_DB_PATH)
    now = datetime.now().isoformat()
    try:
        cursor = conn.cursor()
        
        # Check if session exists
        cursor.execute("SELECT id FROM sessions WHERE id = ?", (session_id,))
        session_exists = cursor.fetchone() is not None
        
        if not session_exists:
            # Generate a title from the first question (first 60 chars)
            title = question[:60] + ("..." if len(question) > 60 else "")
            cursor.execute(
                "INSERT INTO sessions (id, title, username, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                (session_id, title, username, now, now)
            )
        else:
            # Update updated_at
            cursor.execute(
                "UPDATE sessions SET updated_at = ? WHERE id = ?",
                (now, session_id)
            )
            if username:
                cursor.execute(
                    "UPDATE sessions SET username = ? WHERE id = ? AND username IS NULL",
                    (username, session_id)
                )
            
        # Save user message
        user_msg_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO messages (id, session_id, role, content, created_at) VALUES (?, ?, ?, ?, ?)",
            (user_msg_id, session_id, "user", question, now)
        )
        
        # Save assistant message
        assistant_msg_id = str(uuid.uuid4())
        result_json = json.dumps(result) if result is not None else None
        cursor.execute(
            "INSERT INTO messages (id, session_id, role, content, sql, result, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (assistant_msg_id, session_id, "assistant", response_text, sql, result_json, now)
        )
        
        conn.commit()
        return session_id
    except sqlite3.Error as e:
        print(f"Database error while saving chat turn: {e}")
        return session_id
    finally:
        conn.close()


def _http_error_from_exc(exc: Exception) -> HTTPException:
    msg = str(exc)
    model = chat_model_name()
    if "not found" in msg.lower() and "model" in msg.lower():
        return HTTPException(
            status_code=503,
            detail=(
                f"Ollama model '{model}' is not installed. "
                f"Run: ollama pull {model} - then restart uvicorn. ({msg})"
            ),
        )
    return HTTPException(status_code=500, detail=msg)


def _extract_tool_content(message: Any) -> str | None:
    """Extract plain-text content from a ToolMessage.

    MCP adapters may deliver content as a plain string OR as a list of
    content blocks (e.g. [{"type": "text", "text": "..."}]).  Handle both.
    """
    raw = getattr(message, "content", None)
    if raw is None:
        return None
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        for item in raw:
            if isinstance(item, str):
                return item
            if isinstance(item, dict) and item.get("type") == "text":
                return item.get("text")
    return str(raw)


def _extract_sql_and_result(messages: list[Any], username: str) -> AskResponse:
    from langchain_core.messages import ToolMessage as LCToolMessage

    sql = None
    result: list[dict[str, Any]] | None = None

    for message in messages:
        # ── extract SQL from any AIMessage tool call ──────────────────────────
        for tool_call in getattr(message, "tool_calls", None) or []:
            args = tool_call.get("args") or {}
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except json.JSONDecodeError:
                    args = {}
            if tool_call.get("name") == "execute_sql" and args.get("query"):
                sql = args["query"]

        # ── extract rows from any execute_sql ToolMessage ─────────────────────
        is_tool_msg = isinstance(message, LCToolMessage) or (
            message.__class__.__name__ == "ToolMessage"
        )
        if not is_tool_msg:
            continue

        tool_name = getattr(message, "name", None)
        if tool_name != "execute_sql":
            continue

        raw_content = _extract_tool_content(message)
        if not raw_content:
            continue

        try:
            payload = json.loads(raw_content)
        except (json.JSONDecodeError, TypeError, ValueError):
            continue

        if payload.get("status") == "success":
            result = payload.get("rows") or []

    # If SQL was not found, default to empty string
    if sql is None:
        sql = ""

    # If result was not found (meaning failure or no execution), build a fallback explanation result
    if result is None:
        error_msg = None
        # Try to find an error status in execute_sql ToolMessages
        for message in reversed(messages):
            is_tool_msg = isinstance(message, LCToolMessage) or (
                message.__class__.__name__ == "ToolMessage"
            )
            if is_tool_msg and getattr(message, "name", None) == "execute_sql":
                raw_content = _extract_tool_content(message)
                if raw_content:
                    try:
                        payload = json.loads(raw_content)
                        if payload.get("status") == "error":
                            error_msg = payload.get("error_msg") or payload.get("error_type")
                            if error_msg:
                                break
                    except Exception:
                        pass

        # If no tool error, look for any final explanation AIMessage
        if not error_msg:
            for message in reversed(messages):
                msg_class = message.__class__.__name__
                if msg_class == "AIMessage" or getattr(message, "content", None):
                    # Make sure it's not a tool call message
                    if not getattr(message, "tool_calls", None):
                        content = getattr(message, "content", None)
                        if content and isinstance(content, str) and content.strip():
                            error_msg = content.strip()
                            break

        if not error_msg:
            error_msg = "The agent did not return an executed SQL query."

        result = [{"error": error_msg, "status": "failed"}]

    return AskResponse(sql=sql, result=result, username=username)



@asynccontextmanager
async def lifespan(app: FastAPI):
    init_database()
    init_history_database()
    ollama_status = check_ollama()
    app.state.ollama_status = ollama_status
    app.state.graph = None
    app.state.graph_lock = asyncio.Lock()
    if not ollama_status.get("model_available"):
        print("WARNING: Ollama chat model not available:", ollama_status)
    else:
        print("Ollama ready:", ollama_status.get("model"))
        try:
            app.state.graph = await build_graph()
            print("LangGraph agent built successfully during startup.")
        except Exception as e:
            app.state.graph = None
            print(f"Failed to build LangGraph agent during startup: {e}")
            traceback.print_exc()

    yield
    if app.state.graph is not None:
        await cleanup_tools()


async def _get_graph():
    if app.state.graph is None:
        async with app.state.graph_lock:
            if app.state.graph is None:
                app.state.graph = await build_graph()
    return app.state.graph


# Global lock to serialize requests and prevent concurrency crashes in Milvus/MCP
request_lock = asyncio.Lock()

app = FastAPI(
    title="Student Dropout Intent API",
    version="1.4.0",
    description="API backend for natural-language SQL with Intent Classification (v1.4).",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    info = check_ollama()
    return {
        "status": "ok" if info.get("model_available") else "degraded",
        **info,
    }


@app.post("/ask")
async def ask(payload: AskRequest):
    action = payload.action or "ask"
    username = payload.username

    # 1. Action: Cancel
    if action == "cancel":
        req_id = payload.request_id
        if not req_id:
            raise HTTPException(status_code=400, detail="request_id is required for cancel action")
        task = active_tasks.get(req_id)
        if task:
            task.cancel()
            return {"status": "success", "message": f"Request {req_id} cancellation signal sent."}
        return {
            "status": "not_found",
            "message": f"Request {req_id} is not active or has already completed.",
        }

    # 2. Action: History (list all sessions — returns titles and dates only)
    elif action == "history":
        conn = sqlite3.connect(HISTORY_DB_PATH)
        conn.row_factory = sqlite3.Row
        try:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT id, title, created_at, updated_at FROM sessions WHERE username = ? ORDER BY updated_at DESC",
                (username,)
            )
            session_rows = cursor.fetchall()
            sessions = [
                SessionSummary(
                    id=row["id"],
                    title=row["title"],
                    created_at=row["created_at"],
                    updated_at=row["updated_at"],
                )
                for row in session_rows
            ]
            return sessions
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to fetch chat history: {e}")
        finally:
            conn.close()

    # 2b. Action: History Session (fetch full message context for a given session_id)
    elif action == "history_session":
        session_id = payload.session_id or payload.thread_id
        if not session_id:
            raise HTTPException(status_code=400, detail="session_id is required for history_session action")
        conn = sqlite3.connect(HISTORY_DB_PATH)
        conn.row_factory = sqlite3.Row
        try:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT id, title, username, created_at, updated_at FROM sessions WHERE id = ? AND username = ?",
                (session_id, username)
            )
            s_row = cursor.fetchone()
            if not s_row:
                raise HTTPException(status_code=404, detail="Session not found")

            cursor.execute(
                "SELECT id, role, content, sql, result, created_at FROM messages WHERE session_id = ? ORDER BY created_at ASC",
                (session_id,)
            )
            msg_rows = cursor.fetchall()
            messages = []
            for r in msg_rows:
                res_val = None
                if r["result"]:
                    try:
                        res_val = json.loads(r["result"])
                    except Exception:
                        res_val = []
                messages.append(
                    MessageDetail(
                        id=r["id"],
                        role=r["role"],
                        content=r["content"],
                        sql=r["sql"],
                        result=res_val,
                        created_at=r["created_at"],
                    )
                )
            return SessionDetail(
                id=s_row["id"],
                title=s_row["title"],
                created_at=s_row["created_at"],
                updated_at=s_row["updated_at"],
                messages=messages,
            )
        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to fetch session context: {e}")
        finally:
            conn.close()

    # 3. Action: Delete Session
    elif action == "delete_session":
        session_id = payload.session_id or payload.thread_id
        if not session_id:
            raise HTTPException(status_code=400, detail="session_id is required for delete_session action")
        conn = sqlite3.connect(HISTORY_DB_PATH)
        try:
            cursor = conn.cursor()
            cursor.execute("SELECT username FROM sessions WHERE id = ?", (session_id,))
            row = cursor.fetchone()
            if not row or row[0] != username:
                raise HTTPException(status_code=404, detail="Chat session not found")

            cursor.execute("DELETE FROM messages WHERE session_id = ?", (session_id,))
            cursor.execute("DELETE FROM sessions WHERE id = ?", (session_id,))
            conn.commit()
            return {"status": "success", "message": "Session deleted successfully"}
        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to delete session: {e}")
        finally:
            conn.close()

    # 4. Action: Clear History
    elif action == "clear_history":
        conn = sqlite3.connect(HISTORY_DB_PATH)
        try:
            cursor = conn.cursor()
            cursor.execute("DELETE FROM messages WHERE session_id IN (SELECT id FROM sessions WHERE username = ?)", (username,))
            cursor.execute("DELETE FROM sessions WHERE username = ?", (username,))
            conn.commit()
            return {"status": "success", "message": "All sessions deleted successfully"}
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to clear sessions: {e}")
        finally:
            conn.close()

    # 5. Action: Ask (NL2SQL Query)
    elif action == "ask":
        if not payload.question:
            raise HTTPException(status_code=400, detail="question is required for ask action")
        
        req_id = payload.request_id or f"req_{asyncio.get_running_loop().time()}"
        session_id = payload.session_id or payload.thread_id or str(uuid.uuid4())
        history_messages = get_session_messages(session_id)

        async def _stream():
            graph_task: asyncio.Task | None = None
            try:
                if not check_ollama().get("model_available"):
                    yield json.dumps({
                        "sql": "",
                        "result": [{"error": (
                            f"Ollama model '{chat_model_name()}' is not available. "
                            f"Run: ollama pull {chat_model_name()} — then restart uvicorn."
                        ), "status": "failed"}],
                    }).encode()
                    return

                graph = await _get_graph()

                # Run the graph inside the request lock in a background task so we
                # can send periodic keepalive bytes while it works.  IIS (and any
                # reverse proxy) resets its idle-connection timer on every byte
                # received, so this prevents the 502 from triggering before the
                # graph finishes.
                async def _run_graph():
                    async with request_lock:
                        return await graph.ainvoke(
                            {
                                "user_query": payload.question,
                                "messages": history_messages + [HumanMessage(content=payload.question)],
                                "retrieved_context": [],
                                "llm_calls": 0,
                                "verify_calls": 0,
                                "verified": False,
                                # intent_node will populate these during the run
                                "intent": None,
                                "department_scope": None,
                                "entities": None,
                            }
                        )

                graph_task = asyncio.ensure_future(_run_graph())
                active_tasks[req_id] = graph_task

                # Keepalive loop: check if the graph task is done every 0.1 seconds.
                # Every 10 seconds, send a keepalive space to reset IIS proxy timeouts.
                KEEPALIVE_INTERVAL = 10.0
                POLL_INTERVAL = 0.1
                elapsed = 0.0
                while not graph_task.done():
                    await asyncio.sleep(POLL_INTERVAL)
                    elapsed += POLL_INTERVAL
                    if elapsed >= KEEPALIVE_INTERVAL:
                        yield b" "  # keepalive — resets IIS 120 s proxy timeout
                        elapsed = 0.0

                # Retrieve result (re-raises any exception from inside the task)
                state = graph_task.result()
                response_obj = _extract_sql_and_result(state.get("messages", []), username)

                # Extract response text (the final assistant verbal summary)
                response_text = ""
                for msg in reversed(state.get("messages", [])):
                    if msg.__class__.__name__ == "AIMessage" or getattr(msg, "type", None) == "ai":
                        if not getattr(msg, "tool_calls", None) and getattr(msg, "content", ""):
                            response_text = msg.content
                            break
                if not response_text:
                    if response_obj.result and isinstance(response_obj.result, list) and len(response_obj.result) > 0 and "error" in response_obj.result[0]:
                        response_text = response_obj.result[0]["error"]
                    else:
                        response_text = "Here is the query result."

                # Save user query and assistant response to chat history database
                save_chat_turn(
                    session_id=session_id,
                    question=payload.question,
                    response_text=response_text,
                    sql=response_obj.sql,
                    result=response_obj.result,
                    username=username
                )

                response_obj.username = username

                yield json.dumps(response_obj.model_dump()).encode()

            except BaseException as exc:
                cancelled = (
                    (graph_task is not None and graph_task.cancelled())
                    or isinstance(exc, asyncio.CancelledError)
                )
                if cancelled:
                    print(f"Request {req_id} was explicitly cancelled.")
                    yield json.dumps({"sql": "", "result": [{"error": "Request cancelled.", "status": "cancelled"}]}).encode()
                else:
                    traceback.print_exc()
                    yield json.dumps({"sql": "", "result": [{"error": str(exc), "status": "failed"}]}).encode()

            finally:
                active_tasks.pop(req_id, None)

        return StreamingResponse(
            _stream(),
            media_type="application/json",
        )
    else:
        raise HTTPException(status_code=400, detail=f"Unsupported action: {action}")


@app.get("/", response_class=HTMLResponse)
async def get_ui():
    html_content = r"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>⚡ Curated Datamodels Chat App</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Inter', sans-serif;
            background-color: #0b0f19;
            color: #f8fafc;
            display: flex;
            height: 100vh;
            overflow: hidden;
        }
        /* Sidebar Styling */
        .sidebar {
            width: 320px;
            background-color: #070a10;
            border-right: 1px solid #1e293b;
            display: flex;
            flex-direction: column;
            flex-shrink: 0;
        }
        .sidebar-header {
            padding: 24px;
            border-bottom: 1px solid #1e293b;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .sidebar-logo {
            font-size: 20px;
            font-weight: 700;
            background: linear-gradient(135deg, #6366f1, #a855f7);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.5px;
        }
        .config-panel {
            padding: 20px 24px;
            border-bottom: 1px solid #1e293b;
            display: flex;
            flex-direction: column;
            gap: 12px;
        }
        .config-label {
            font-size: 11px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            color: #94a3b8;
        }
        .config-input-group {
            display: flex;
            gap: 8px;
        }
        .input-text {
            background-color: #111827;
            border: 1px solid #374151;
            border-radius: 8px;
            padding: 10px 14px;
            color: #f8fafc;
            font-size: 13px;
            flex-grow: 1;
            transition: all 0.2s;
        }
        .input-text:focus {
            outline: none;
            border-color: #6366f1;
            box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.2);
        }
        .btn {
            background: linear-gradient(135deg, #4f46e5, #6366f1);
            color: white;
            border: none;
            border-radius: 8px;
            padding: 10px 16px;
            font-size: 13px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 6px;
            user-select: none;
        }
        .btn:hover {
            opacity: 0.95;
            transform: translateY(-1px);
        }
        .btn-secondary {
            background: #1f2937;
            border: 1px solid #374151;
            color: #f8fafc;
        }
        .btn-secondary:hover {
            background: #374151;
        }
        .btn-danger {
            background: #991b1b;
        }
        .btn-danger:hover {
            background: #b91c1c;
        }
        .sessions-list-container {
            flex-grow: 1;
            overflow-y: auto;
            padding: 16px 20px;
        }
        .session-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 14px;
            border-radius: 8px;
            cursor: pointer;
            margin-bottom: 8px;
            transition: all 0.2s;
            border: 1px solid transparent;
            background: rgba(30, 41, 59, 0.2);
        }
        .session-item:hover {
            background: rgba(30, 41, 59, 0.4);
            border-color: #334155;
        }
        .session-item.active {
            background: rgba(99, 102, 241, 0.15);
            border-color: #4f46e5;
        }
        .session-info {
            display: flex;
            flex-direction: column;
            gap: 4px;
            overflow: hidden;
            flex-grow: 1;
        }
        .session-title {
            font-size: 13px;
            font-weight: 500;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .session-date {
            font-size: 11px;
            color: #64748b;
        }
        .btn-delete {
            background: transparent;
            border: none;
            color: #94a3b8;
            cursor: pointer;
            padding: 4px;
            border-radius: 4px;
            display: flex;
            align-items: center;
            justify-content: center;
            opacity: 0;
            transition: all 0.2s;
        }
        .session-item:hover .btn-delete {
            opacity: 1;
        }
        .btn-delete:hover {
            color: #ef4444;
            background: rgba(239, 68, 68, 0.1);
        }
        /* Chat Area Styling */
        .chat-area {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            background-color: #0f172a;
        }
        .chat-header {
            padding: 20px 24px;
            border-bottom: 1px solid #1e293b;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: rgba(15, 23, 42, 0.6);
            backdrop-filter: blur(10px);
        }
        .chat-title-group {
            display: flex;
            flex-direction: column;
            gap: 4px;
        }
        .chat-title {
            font-size: 15px;
            font-weight: 600;
        }
        .chat-subtitle {
            font-size: 11px;
            color: #94a3b8;
            font-family: var(--font-mono);
        }
        .messages-container {
            flex-grow: 1;
            overflow-y: auto;
            padding: 30px 40px;
            display: flex;
            flex-direction: column;
            gap: 24px;
        }
        .message-row {
            display: flex;
            width: 100%;
        }
        .message-row.user {
            justify-content: flex-end;
        }
        .message-row.assistant {
            justify-content: flex-start;
        }
        .bubble {
            max-width: 80%;
            border-radius: 16px;
            padding: 16px 20px;
            line-height: 1.5;
            font-size: 14px;
        }
        .message-row.user .bubble {
            background-color: #312e81;
            color: #f8fafc;
            border-bottom-right-radius: 4px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .message-row.assistant .bubble {
            background-color: #1e293b;
            color: #f8fafc;
            border-bottom-left-radius: 4px;
            border: 1px solid #334155;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            gap: 14px;
        }
        .bubble-text {
            white-space: pre-wrap;
        }
        /* Collapsible Accordions */
        details {
            background: #0f172a;
            border: 1px solid #334155;
            border-radius: 8px;
            overflow: hidden;
            transition: all 0.2s;
            width: 100%;
        }
        details[open] {
            border-color: #4f46e5;
        }
        summary {
            padding: 12px 16px;
            font-size: 12px;
            font-weight: 600;
            color: #94a3b8;
            cursor: pointer;
            user-select: none;
            display: flex;
            align-items: center;
            gap: 8px;
            outline: none;
            transition: background 0.2s;
        }
        summary:hover {
            background: rgba(255, 255, 255, 0.02);
            color: #f8fafc;
        }
        .code-block {
            padding: 16px;
            background: #090d16;
            border-top: 1px solid #334155;
            font-family: var(--font-mono);
            font-size: 12px;
            color: #38bdf8;
            overflow-x: auto;
            white-space: pre-wrap;
        }
        /* Results Table */
        .results-container {
            border-top: 1px solid #334155;
            overflow-x: auto;
            max-height: 250px;
            overflow-y: auto;
        }
        .results-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
            text-align: left;
        }
        .results-table th {
            background-color: #070a10;
            color: #94a3b8;
            font-weight: 600;
            padding: 10px 14px;
            border-bottom: 2px solid #334155;
            position: sticky;
            top: 0;
        }
        .results-table td {
            padding: 10px 14px;
            border-bottom: 1px solid #1e293b;
            color: #e2e8f0;
        }
        .results-table tr:hover {
            background-color: rgba(255, 255, 255, 0.02);
        }
        .error-card {
            background: rgba(239, 68, 68, 0.1);
            border: 1px solid #ef4444;
            color: #fca5a5;
            border-radius: 8px;
            padding: 12px 16px;
            font-size: 13px;
            display: flex;
            align-items: center;
            gap: 8px;
        }
        /* Input Panel Styling */
        .input-panel {
            padding: 24px 40px;
            border-top: 1px solid #1e293b;
            background: rgba(15, 23, 42, 0.8);
        }
        .input-form {
            display: flex;
            gap: 12px;
        }
        .input-chat {
            background-color: #111827;
            border: 1px solid #374151;
            border-radius: 12px;
            padding: 16px 20px;
            color: #f8fafc;
            font-size: 14px;
            flex-grow: 1;
            resize: none;
            height: 54px;
            transition: all 0.2s;
        }
        .input-chat:focus {
            outline: none;
            border-color: #6366f1;
            box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.2);
        }
        /* Loader and Status */
        .loader {
            border: 3px solid #334155;
            border-top: 3px solid #6366f1;
            border-radius: 50%;
            width: 20px;
            height: 20px;
            animation: spin 1s linear infinite;
            display: inline-block;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .loading-state {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 20px;
            color: #94a3b8;
            font-size: 13px;
        }
        .empty-chat {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
            color: #64748b;
            text-align: center;
            gap: 16px;
        }
        .empty-icon {
            font-size: 48px;
            color: #334155;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <div class="sidebar-header">
            <div class="sidebar-logo">⚡ dropout.ai</div>
        </div>
        <div class="config-panel">
            <div class="config-label">Username (Scoping)</div>
            <div class="config-input-group">
                <input type="text" id="usernameInput" class="input-text" placeholder="e.g. test_user" value="test_user">
                <button class="btn btn-secondary" onclick="loadHistory()">Load</button>
            </div>
            <button class="btn" style="margin-top: 8px;" onclick="startNewSession()">+ New Session</button>
        </div>
        <div class="sessions-list-container" id="sessionsList">
            <!-- Session items will populate here -->
        </div>
        <div class="config-panel" style="border-top: 1px solid #1e293b; border-bottom: none;">
            <button class="btn btn-secondary btn-danger" onclick="clearAllHistory()">Clear All History</button>
        </div>
    </div>
    
    <div class="chat-area">
        <div class="chat-header">
            <div class="chat-title-group">
                <div class="chat-title" id="chatTitle">Select or Start a Chat Session</div>
                <div class="chat-subtitle" id="chatSubtitle">No Active Session</div>
            </div>
        </div>
        
        <div class="messages-container" id="messagesContainer">
            <div class="empty-chat">
                <div class="empty-icon">💬</div>
                <div>Enter a username on the left, then click "Load" to start browsing sessions or submit a query.</div>
            </div>
        </div>
        
        <div class="input-panel">
            <form class="input-form" onsubmit="submitQuestion(event)">
                <textarea id="questionInput" class="input-chat" placeholder="Ask a natural-language database question..." onkeydown="handleEnter(event)"></textarea>
                <button class="btn" type="submit" id="sendBtn" style="height: 54px; width: 80px;">Send</button>
            </form>
        </div>
    </div>

    <script>
        let currentUsername = "";
        let currentSessionId = "";
        let sessionsMap = new Map(); // session_id -> session object

        // Helper to generate UUIDv4
        function generateUUID() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

        // On document load, configure username and fetch history
        window.addEventListener('DOMContentLoaded', () => {
            const savedUsername = localStorage.getItem('chat_username') || 'test_user';
            document.getElementById('usernameInput').value = savedUsername;
            loadHistory();
        });

        function handleEnter(event) {
            if (event.key === 'Enter' && !event.shiftKey) {
                event.preventDefault();
                submitQuestion(event);
            }
        }

        async function loadHistory() {
            const usernameInput = document.getElementById('usernameInput');
            currentUsername = usernameInput.value.trim();
            if (!currentUsername) {
                alert("Please enter a username.");
                return;
            }
            localStorage.setItem('chat_username', currentUsername);
            
            try {
                const response = await fetch('/ask', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'history',
                        username: currentUsername
                    })
                });
                if (!response.ok) throw new Error("Failed to load history");
                
                const sessions = await response.json();
                sessionsMap.clear();
                
                const listContainer = document.getElementById('sessionsList');
                listContainer.innerHTML = '';
                
                sessions.forEach(session => {
                    sessionsMap.set(session.id, session);
                    
                    const item = document.createElement('div');
                    item.className = `session-item ${session.id === currentSessionId ? 'active' : ''}`;
                    item.id = `session-${session.id}`;
                    item.onclick = () => selectSession(session.id);
                    
                    const formattedDate = new Date(session.updated_at).toLocaleString();
                    
                    item.innerHTML = `
                        <div class="session-info">
                            <div class="session-title">${escapeHtml(session.title)}</div>
                            <div class="session-date">${formattedDate}</div>
                        </div>
                        <button class="btn-delete" onclick="deleteSession(event, '${session.id}')">
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                        </button>
                    `;
                    listContainer.appendChild(item);
                });
                
                if (currentSessionId && sessionsMap.has(currentSessionId)) {
                    selectSession(currentSessionId);
                } else if (sessions.length > 0) {
                    selectSession(sessions[0].id);
                } else {
                    startNewSession();
                }
            } catch (err) {
                console.error(err);
                alert("Error retrieving history.");
            }
        }

        function selectSession(sessionId) {
            currentSessionId = sessionId;
            document.querySelectorAll('.session-item').forEach(el => el.classList.remove('active'));
            const activeEl = document.getElementById(`session-${sessionId}`);
            if (activeEl) activeEl.classList.add('active');
            
            const session = sessionsMap.get(sessionId);
            if (session) {
                document.getElementById('chatTitle').innerText = session.title;
                document.getElementById('chatSubtitle').innerText = `Session ID: ${session.id}`;
                
                // Render session messages
                const container = document.getElementById('messagesContainer');
                container.innerHTML = '';
                
                session.messages.forEach(msg => {
                    renderMessage(msg.role, msg.content, msg.sql, msg.result);
                });
                scrollToBottom();
            }
        }

        function startNewSession() {
            currentSessionId = generateUUID();
            document.querySelectorAll('.session-item').forEach(el => el.classList.remove('active'));
            
            document.getElementById('chatTitle').innerText = "New Chat Session";
            document.getElementById('chatSubtitle').innerText = `Session ID: ${currentSessionId}`;
            
            const container = document.getElementById('messagesContainer');
            container.innerHTML = `
                <div class="empty-chat">
                    <div class="empty-icon">💬</div>
                    <div>This is a new conversation thread. Type your question below to begin.</div>
                </div>
            `;
            scrollToBottom();
        }

        async function deleteSession(event, sessionId) {
            event.stopPropagation();
            if (!confirm("Are you sure you want to delete this session?")) return;
            
            try {
                const response = await fetch('/ask', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'delete_session',
                        username: currentUsername,
                        session_id: sessionId
                    })
                });
                if (!response.ok) throw new Error("Delete failed");
                
                if (currentSessionId === sessionId) {
                    currentSessionId = "";
                }
                loadHistory();
            } catch (err) {
                alert("Failed to delete session.");
            }
        }

        async function clearAllHistory() {
            if (!confirm("Are you sure you want to clear ALL session history for this user? This cannot be undone.")) return;
            
            try {
                const response = await fetch('/ask', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'clear_history',
                        username: currentUsername
                    })
                });
                if (!response.ok) throw new Error("Clear failed");
                currentSessionId = "";
                loadHistory();
            } catch (err) {
                alert("Failed to clear history.");
            }
        }

        function renderMessage(role, text, sql = null, result = null) {
            const container = document.getElementById('messagesContainer');
            
            // Remove empty chat state if present
            const emptyState = container.querySelector('.empty-chat');
            if (emptyState) emptyState.remove();
            
            const row = document.createElement('div');
            row.className = `message-row ${role === 'user' ? 'user' : 'assistant'}`;
            
            const bubble = document.createElement('div');
            bubble.className = 'bubble';
            
            const textDiv = document.createElement('div');
            textDiv.className = 'bubble-text';
            textDiv.innerHTML = formatMarkdown(text);
            bubble.appendChild(textDiv);
            
            // If it is assistant and has SQL/Results, append details accordions
            if (role === 'assistant') {
                if (sql) {
                    const sqlDetails = document.createElement('details');
                    sqlDetails.innerHTML = `
                        <summary>
                            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>
                            Generated SQL
                        </summary>
                        <div class="code-block">${escapeHtml(sql)}</div>
                    `;
                    bubble.appendChild(sqlDetails);
                }
                
                if (result) {
                    const resultDetails = document.createElement('details');
                    const isError = result.length > 0 && (result[0].status === 'failed' || result[0].status === 'cancelled');
                    
                    let resultHtml = "";
                    if (isError) {
                        const errorTitle = result[0].status === 'cancelled' ? 'Request Cancelled' : 'Execution Failure';
                        const cardStyle = result[0].status === 'cancelled' ? 'border-color: #f59e0b; color: #fcd34d; background: rgba(245, 158, 11, 0.1);' : '';
                        resultHtml = `
                            <summary style="color: #fca5a5;">
                                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
                                ${errorTitle}
                            </summary>
                            <div class="error-card" style="${cardStyle}">
                                <strong>Status:</strong> ${escapeHtml(result[0].error || 'Query execution failed')}
                            </div>
                        `;
                    } else {
                        resultHtml = `
                            <summary>
                                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line><line x1="15" y1="3" x2="15" y2="21"></line><line x1="3" y1="9" x2="21" y2="9"></line><line x1="3" y1="15" x2="21" y2="15"></line></svg>
                                Query Results (${result.length} rows)
                            </summary>
                            <div class="results-container">
                                ${renderTable(result)}
                            </div>
                        `;
                    }
                    resultDetails.innerHTML = resultHtml;
                    bubble.appendChild(resultDetails);
                }
            }
            
            row.appendChild(bubble);
            container.appendChild(row);
            scrollToBottom();
        }

        async function submitQuestion(event) {
            event.preventDefault();
            const inputEl = document.getElementById('questionInput');
            const question = inputEl.value.trim();
            if (!question) return;
            
            inputEl.value = '';
            
            // Render user query bubble immediately
            renderMessage('user', question);
            
            const reqId = "req_" + Date.now();
            
            // Render loader spinner
            const container = document.getElementById('messagesContainer');
            const loadingRow = document.createElement('div');
            loadingRow.className = 'message-row assistant';
            loadingRow.id = 'loadingStateRow';
            loadingRow.innerHTML = `
                <div class="loading-state">
                    <span class="loader"></span>
                    <span>AI Agent is thinking and executing database tools...</span>
                    <button class="btn btn-secondary btn-danger" style="padding: 6px 12px; font-size: 11px; margin-left: 10px;" onclick="triggerCancel('${reqId}')">Cancel</button>
                </div>
            `;
            container.appendChild(loadingRow);
            scrollToBottom();
            
            try {
                const response = await fetch('/ask', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'ask',
                        question: question,
                        username: currentUsername,
                        session_id: currentSessionId,
                        request_id: reqId
                    })
                });
                
                if (!response.ok) throw new Error("Ask failed");
                
                // Read streaming response
                const reader = response.body.getReader();
                const decoder = new TextDecoder();
                let buffer = "";
                
                while (true) {
                    const { value, done } = await reader.read();
                    if (done) break;
                    buffer += decoder.decode(value, { stream: true });
                }
                
                // Clean up loader
                const loader = document.getElementById('loadingStateRow');
                if (loader) loader.remove();
                
                buffer = buffer.trim();
                const data = JSON.parse(buffer);
                
                // Load details of the response text
                let explanation = "Here is the result of your query.";
                if (data.result && data.result.length > 0) {
                    if (data.result[0].status === 'failed') {
                        explanation = data.result[0].error || "The query execution failed.";
                    } else if (data.result[0].status === 'cancelled') {
                        explanation = "The request was cancelled.";
                    }
                }
                
                // If it was cancelled, render the cancelled response directly
                if (data.result && data.result.length > 0 && data.result[0].status === 'cancelled') {
                    renderMessage('assistant', "Request cancelled by user.", data.sql, data.result);
                }
                
                // Re-fetch history to update sidebar with the new turn details
                await loadHistory();
                
            } catch (err) {
                console.error(err);
                const loader = document.getElementById('loadingStateRow');
                if (loader) loader.remove();
                renderMessage('assistant', "An error occurred while communicating with the agent server.", null, [{status: 'failed', error: err.message}]);
            }
        }

        async function triggerCancel(reqId) {
            try {
                const response = await fetch('/ask', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'cancel',
                        username: currentUsername,
                        request_id: reqId
                    })
                });
                const result = await response.json();
                console.log("Cancel triggered response:", result);
            } catch (err) {
                console.error("Failed to call /cancel:", err);
            }
        }

        function renderTable(rows) {
            if (!rows || rows.length === 0) return "<div style='padding: 12px; font-style: italic; color: #64748b;'>Empty results set</div>";
            
            const keys = Object.keys(rows[0]);
            let html = "<table class='results-table'><thead><tr>";
            keys.forEach(k => {
                html += `<th>${escapeHtml(k)}</th>`;
            });
            html += "</tr></thead><tbody>";
            
            rows.forEach(row => {
                html += "<tr>";
                keys.forEach(k => {
                    let val = row[k];
                    if (typeof val === 'object' && val !== null) {
                        val = JSON.stringify(val);
                    } else if (val === null) {
                        val = "<span style='color: #475569;'>NULL</span>";
                    }
                    html += `<td>${val}</td>`;
                });
                html += "</tr>";
            });
            html += "</tbody></table>";
            return html;
        }

        function scrollToBottom() {
            const container = document.getElementById('messagesContainer');
            container.scrollTop = container.scrollHeight;
        }

        function escapeHtml(str) {
            if (typeof str !== 'string') return str;
            return str
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }

        function formatMarkdown(text) {
            if (!text) return "";
            let escaped = escapeHtml(text);
            
            // Format bold text
            escaped = escaped.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
            escaped = escaped.replace(/\*(.*?)\*/g, "<em>$1</em>");
            
            // Format inline code
            escaped = escaped.replace(/`(.*?)`/g, "<code style='font-family: var(--font-mono); background-color: #090d16; padding: 2px 6px; border-radius: 4px; color: #38bdf8;'>$1</code>");
            
            return escaped;
        }
    </script>
</body>
</html>
"""
    return HTMLResponse(content=html_content)

